#!/bin/bash

# add pi user to group

# @example
# add user to "disk" and "staff" group
# RPI_ADDUSER_GROUP=( "disk" "staff" )


# default options
commarray RPI_ADDUSER_GROUP

# load dependencies
plugin_load run || return 1


rpi_adduser_prerun() {
    [[ -n "${RPI_ADDUSER_GROUP}" ]] || error "RPI_ADDUSER_GROUP not set. adduser"
}

rpi_adduser_run() {
    for g in "${RPI_ADDUSER_GROUP[@]}" ; do
        rpi_run_once "sudo adduser pi ${g}" || error "add to group ${g}"
    done
}

rpi_adduser_description() {
    echo "add pi user to group"
}

rpi_adduser_help_params() {
    help_param "RPI_ADDUSER_GROUP" "group to add user to"
}
