#!/bin/bash

# apt jobs to run upon first login

# @example
# update, upgrade and autoremove
# RPI_APT_CMDS=( "update" "full-upgrade" "autoremove" )


# default options
RPI_APT_INTERACTIVE="${RPI_APT_INTERACTIVE:=false}"
to_array RPI_APT_CMDS

# load dependencies
plugin_load run || return 1


rpi_apt_prerun() {
    [[ -n "${RPI_APT_CMDS}" ]] || return 1
    return 0
}

rpi_apt_run() {
    local cmd
    for cmd in "${RPI_APT_CMDS[@]}" ; do
        # run in interactive mode?
        if [[ "${RPI_APT_INTERACTIVE}" == "true" ]] ; then
            RPI_RUN_ONCE=true rpi_run "sudo apt ${cmd}" || error "apt"
        # run in non-interactive mode
        else
            RPI_RUN_ONCE=true rpi_run "sudo DEBIAN_FRONTEND=noninteractive apt --yes --quiet ${cmd}" || error "install apt update"
        fi
    done
}

function rpi_apt_description() {
    echo "run apt commands"
}

function rpi_apt_help_params() {
    help_param "RPI_APT_CMDS" "array of apt commands to execute"
    help_param "RPI_APT_INTERACTIVE" "run in interactive mode"
}
