#!/bin/bash

# ask for user input interactively
# (@todo either on image bootstrap or on first boot)

# @example
# ask user for current mood and store answer in RPI_MOOD variable
# RPI_ASK_QUESTION0="How are you?"
# RPI_ASK_VARIABLE0="RPI_MOOD"

# @example
# ask user for mood but use GUI zenity instead of CLI read
# RPI_ASK_QUESTION0="How are you?"
# RPI_ASK_VARIABLE0="RPI_MOOD"
# RPI_ASK_METHOD="zenity"

# @example
# ask user for mood and pass custom parameters to zenity
# RPI_ASK_QUESTION0="How are you?"
# RPI_ASK_VARIABLE0="RPI_MOOD"
# RPI_ASK_ARGUMENTS0="--entry,--entry-text=totally\ fine,--title=the\ big\ questions..."


# @todo
# RPI_ASK_METHOD="${RPI_ASK_METHOD:=read}"
RPI_ASK_ON="${RPI_ASK_ON:=bootstrap}"



function rpi_ask_prerun() {
    [[ -n "${RPI_ASK_QUESTION0}" ]] || error "RPI_ASK_QUESTION0 not set"
    [[ -n "${RPI_ASK_VARIABLE0}" ]] || error "RPI_ASK_VARIABLE0 not set"
    return 0
}

function rpi_ask_run() {
    local i=0
    local destvar
    local argsvar
    local questionvar="RPI_ASK_QUESTION0"
    while [[ -n "${!questionvar+x}" ]] ; do
        destvar="RPI_ASK_VARIABLE${i}"
        argsvar="RPI_ASK_ARGUMENTS${i}"
        ask "${!questionvar}" "${argsvar}"
        # export target variable
        log "setting: ${!destvar}=\"${answer}\""
        export "${!destvar}=\"${answer}\""
        # next question
        i=$((i+1))
        questionvar="RPI_ASK_QUESTION${i}"
    done
}

function rpi_ask_description() {
    echo "ask for input"
}

function rpi_ask_help_params() {
    # @todo
    #help_param "RPI_ASK_METHOD" "the asking method (One of: read, zenity)"
    help_param "RPI_ASK_ON" "when to ask question: \"bootstrap\" or \"boot\""
    help_param "RPI_ASK_QUESTIONn" "question number n (starting from 0)"
    help_param "RPI_ASK_VARIABLEn" "name of variable to store answer for question n"
    help_param "RPI_ASK_ARGUMENTSn" "method specific arguments to pass to method (s. manual of specific method)"
}

# ---------------------------------------------------------------------
function ask() {
    local args
    local argsvar="${2}"
    declare -n args="${argsvar}"
    commarray "${argsvar}"

    case "${RPI_ASK_METHOD}" in
        "read")
            echo -n "$1 : "
            read -r answer
            ;;

        "zenity")
            [[ -n "${args[*]}" ]] || args=("--entry")
            answer=$(zenity "${args[@]}" --text "$1" || error "zenity aborted or")
            ;;

        ?|*)
            error "unknown RPI_ASK_METHOD: \"${OPTARG}\""
            ;;
    esac


}
