#!/bin/bash

# customize config.txt


function rpi_config_prerun() {
    true
}

function rpi_config_run() {
    for c in "${RPI_CONFIG_ADD[@]}" ; do
        echo " setting ${c} ..."
        append_to_file "${c}" "${RPI_BOOT}/config.txt" || error "adding ${c}"
    done

    for c in "${RPI_CONFIG_REMOVE[@]}" ; do
        echo " removing ${c} ..."
        remove_line_from_file "${c}" "${RPI_BOOT}/config.txt" || error "removing ${c}"
    done

    cp_from_dist_if_exist "/boot/config.txt"

    return 0
}

function rpi_config_description() {
    echo "modify /boot/config.txt"
}

function rpi_config_help_vars() {
    vars=( \
        "RPI_CONFIG_ADD|\"key=value\" pairs to append to config.txt|${RPI_CONFIG_ADD}" \
        "RPI_CONFIG_REMOVE|\"key=value\" pairs to delete from config.txt|${RPI_CONFIG_REMOVE}" \
    )
    help_for_vars "${vars}"
}

function rpi_config_help_distfiles() {
    distfiles=( "/boot/config.txt" )
    help_for_distfiles "${distfiles}"
}
