#!/bin/bash

# customize config.txt


function rpi_config_prerun() {
    # load dependencies
    plugin_load append || return 1
    plugin_load remove || return 1
}

function rpi_config_run() {
    local c
    for c in "${RPI_CONFIG_ADD[@]}" ; do
        echo " setting ${c} ..."
        rpi_append_to_file "${c}" "${RPI_BOOT}/config.txt" || error "adding ${c}"
    done

    for c in "${RPI_CONFIG_REMOVE[@]}" ; do
        echo " removing ${c} ..."
        rpi_remove_line_from_file "${c}" "${RPI_BOOT}/config.txt" || error "removing ${c}"
    done

    cp_from_dist_if_exist "/boot/config.txt"

    return 0
}

function rpi_config_description() {
    echo "modify /boot/config.txt"
}

function rpi_config_help_vars() {
    local vars=(
        "RPI_CONFIG_ADD|\"key=value\" pairs to append to config.txt|${RPI_CONFIG_ADD}"
        "RPI_CONFIG_REMOVE|\"key=value\" pairs to delete from config.txt|${RPI_CONFIG_REMOVE}"
    )
    help_for_vars "${vars[@]}"
}

function rpi_config_help_distfiles() {
    distfiles=( "/boot/config.txt" )
    help_for_distfiles "${distfiles[@]}"
}
