#!/bin/bash

# customize config.txt

# default options
RPI_CONFIG_ADD="${RPI_CONFIG_ADD:=}"
RPI_CONFIG_REMOVE="${RPI_CONFIG_REMOVE:=}"

# load dependencies
plugin_load append || return 1
plugin_load remove || return 1
plugin_load dist || return 1


function rpi_config_prerun() {
    true
}

function rpi_config_run() {
    local c
    for c in "${RPI_CONFIG_ADD[@]}" ; do
        echo " setting ${c} ..."
        rpi_append_to_file "${c}" "${RPI_BOOT}/config.txt" || error "adding ${c}"
    done

    for c in "${RPI_CONFIG_REMOVE[@]}" ; do
        echo " removing ${c} ..."
        rpi_remove_pattern_from_file "${c}" "${RPI_BOOT}/config.txt" || error "removing ${c}"
    done

    rpi_dist_cp_if_exist "/boot/config.txt"

    return 0
}

function rpi_config_description() {
    echo "modify /boot/config.txt"
}

function rpi_config_help_vars() {
    help_var "RPI_CONFIG_ADD" "\"key=value\" pairs to append to config.txt"
    help_var "RPI_CONFIG_REMOVE" "\"key=value\" pairs to delete from config.txt"

}

function rpi_config_help_distfiles() {
    help_distfile "/boot/config.txt"
}
