#!/bin/bash

# download a file from the internet

RPI_DOWNLOAD_URL="${RPI_DOWNLOAD_URL:=}"
RPI_DOWNLOAD_FILE="${RPI_DOWNLOAD_FILE:=}"


rpi_download_prerun() {
    # check arguments
    [[ -n "${RPI_DOWNLOAD_URL}" ]] || error "RPI_DOWNLOAD_URL check"
    [[ -n "${RPI_DOWNLOAD_FILE}" ]] || error "RPI_DOWNLOAD_FILE check"
    # check if wget or curl is available
    command -v wget >/dev/null 2>&1 || \
    command -v curl >/dev/null 2>&1 || error "find wget or curl"
}

rpi_download_run() {
    # got URL or path?
    if echo "${RPI_DOWNLOAD_URL}" | grep --quiet -E '^(https|http|ftp):/.+$'; then
        # download image
        if command -v wget >/dev/null 2>&1 ; then
            wget --show-progress --quiet --output-document "${RPI_DOWNLOAD_FILE}" "${RPI_DOWNLOAD_URL}" || error "wget"
        elif command -v curl >/dev/null 2>&1 ; then
            curl --output "${RPI_DOWNLOAD_FILE}" "${RPI_DOWNLOAD_URL}" || error "curl"
        else
            error "no wget or curl found. ${RPI_DOWNLOAD_URL} fetch"
        fi
    # treat url as path
    else
        cp "${RPI_DOWNLOAD_URL}" "${RPI_DOWNLOAD_FILE}" || error "cp"
    fi

    return 0
}

rpi_download_description() {
    echo "download url"
}

rpi_download_help_vars() {
    local vars=(
        "RPI_DOWNLOAD_URL|url or path to file|${RPI_DOWNLOAD_URL}"
        "RPI_DOWNLOAD_FILE|path to destination file|${RPI_DOWNLOAD_FILE}"
    )
    help_for_vars "${vars[@]}"
}
