#!/bin/bash

# bootstrap hostname of rpi image

RPI_HOSTNAME="${RPI_HOSTNAME:=unnamed}"


function rpi_hostname_prerun() {
    # check arguments
    [[ -n "${RPI_HOSTNAME}" ]] || error "RPI_HOSTNAME not set."
    # load dependencies
    plugin_load append || return 1
    plugin_load dist || return 1

    return 0
}

function rpi_hostname_run() {
    echo " setting hostname to \"${RPI_HOSTNAME}\""
    # create from config parameters
    if [[ -n "${RPI_HOSTNAME}" ]] ; then
        # /etc/hostname
        echo " setting /etc/hostname"
        sudo rm -f "${RPI_ROOT}/etc/hostname"
        rpi_append_to_file "${RPI_HOSTNAME}" "${RPI_ROOT}/etc/hostname"
    fi
    # copy distfile
    rpi_dist_cp_if_exist /etc/hostname
    rpi_dist_cp_if_exist /etc/hosts

    # /etc/hosts
    RPI_HOSTNAME="$(cat "${RPI_ROOT}/etc/hostname")"
    # hostname already in /etc/hosts?
    if ! grep "${RPI_HOSTNAME}" "${RPI_ROOT}/etc/hosts" >/dev/null ; then
        echo " processing /etc/hosts"
        sudo sed "s|raspberrypi|${RPI_HOSTNAME}|g" -i "${RPI_ROOT}/etc/hosts"
    fi
    return 0
}

function rpi_hostname_description() {
    echo "configure hostname"
}

function rpi_hostname_help_vars() {
    local vars=(
        "RPI_HOSTNAME|hostname to set|${RPI_HOSTNAME}"
    )
    help_for_vars "${vars[@]}"
}

function rpi_hostname_help_distfiles() {
    local distfiles=(
        "/etc/hostname"
        "/etc/hosts"
    )
    help_for_distfiles "${distfiles[@]}"
}
