#!/bin/sh

# bootstrap hostname of rpi image


function rpi_hostname_prerun() {
    if [ -z "${RPI_HOSTNAME}" ] ; then
        error "RPI_HOSTNAME not set."
        return 1
    fi

    return 0
}

function rpi_hostname_run() {
    echo " setting hostname to \"${RPI_HOSTNAME}\""
    # create from config parameters
    if [ -n "${RPI_HOSTNAME}" ] ; then
        # /etc/hostname
        echo " setting /etc/hostname"
        sudo rm -f "${RPI_ROOT}/etc/hostname"
        append_to_file "${RPI_HOSTNAME}" "${RPI_ROOT}/etc/hostname"
    fi
    # copy distfile
    cp_from_dist_if_exist /etc/hostname
    cp_from_dist_if_exist /etc/hosts

    # /etc/hosts
    RPI_HOSTNAME="$(cat "${RPI_ROOT}/etc/hostname")"
    # hostname already in /etc/hosts?
    if ! grep "${RPI_HOSTNAME}" "${RPI_ROOT}/etc/hosts" >/dev/null ; then
        echo " processing /etc/hosts"
        sudo sed "s|raspberrypi|${RPI_HOSTNAME}|g" -i "${RPI_ROOT}/etc/hosts"
    fi
    return 0
}
