#!/bin/bash

# setup loopback device & mount image

# default options
RPI_LOOPBACK_IMAGE="${RPI_LOOPBACK_IMAGE:=}"


rpi_loopback_prerun() {
    # check arguments
    [[ -n "${RPI_LOOPBACK_IMAGE}" ]] || error "RPI_LOOPBACK_IMAGE check"
}

rpi_loopback_run() {
    rpi_loopback_setup "${RPI_LOOPBACK_IMAGE}" || return 1
    rpi_loopback_mount || return 1
    return 0
}

rpi_loopback_postrun() {
    # unmount partitions
    rpi_loopback_umount
    # tear down loopback device
    rpi_loopback_cleanup
}

rpi_loopback_description() {
    echo "setup loopback device & mount image"
}

rpi_loopback_help_vars() {
    help_var "RPI_BOOT" "mountpoint for BOOT partition"
    help_var "RPI_ROOT" "mountpoint for root partition"
    help_var "RPI_LOOPBACK_IMAGE" "image filename"
    help_var "RPI_LOOPBACK_DEVICE" "will be set to used /dev/loopX device"
}

# ---------------------------------------------------------------------

# setup loopback device to mount image
function rpi_loopback_setup() {
    local image="$1"
    # argument valid?
    [[ -f "${image}" ]] || error "${image} not found"
    # already attached?
    local device
    device="$(sudo losetup -l | grep "$(basename "${image}")" | cut -d " " -f1)"
    if [[ -z "${device}" ]] ; then
        # attach image
        device="$(sudo losetup --show --find --partscan "${image}")" || error losetup
    fi
    echo " using \"${device}\""
    # store device
    RPI_LOOPBACK_DEVICE="${device}"
    # store img name
    RPI_LOOPBACK_IMAGE="${image}"
}

# tear down loopback device
function rpi_loopback_cleanup() {
    sudo losetup -d "${RPI_LOOPBACK_DEVICE}" || warn "${RPI_LOOPBACK_DEVICE} cleanup failed"
    sync || warn "sync"
}

# mount raspberry image
function rpi_loopback_mount() {
    echo " mounting image..."
    # already mounted?
    mount | grep --quiet "${RPI_LOOPBACK_DEVICE}" && return 0
    # wait for sync
    sync
    # mount
    sudo mount "${RPI_LOOPBACK_DEVICE}p1" "${RPI_BOOT}" || return 1
    sudo mount "${RPI_LOOPBACK_DEVICE}p2" "${RPI_ROOT}" || return 1
    return 0
}

# unmount raspberry image
function rpi_loopback_umount() {
    sudo "umount" "${RPI_BOOT}" || warn "${RPI_BOOT} not mounted"
    sudo "umount" "${RPI_ROOT}" || warn "${RPI_ROOT} not mounted"
}

