#!/bin/sh

# change password on image

RPI_PASSWORD_USER="${RPI_PASSWORD_USER:=pi}"
RPI_PASSWORD_PW="${RPI_PASSWORD_PW:=""}"
RPI_PASSWORD_CRYPT_METHOD="${RPI_PASSWORD_CRYPT_METHOD:=SHA512}"

function rpi_password_prerun() {
    [ -n "${RPI_PASSWORD_USER}" ] || exit "no USER set. password plugin"

    if [ -z "${RPI_PASSWORD_PW}" ] ; then
        # interactively get password
        echo "enter password: "
        read -s password_one
        echo "enter password again: "
        read -s password_two
        [ "${password_one}" == "${password_two}" ] || error "passwords don't match. password plugin"
        # use this password
        RPI_PASSWORD_PW="${password_one}"
        unset password_one
        unset password_two
        return 1
    fi

    return 0
}

function rpi_password_run() {
    echo " setting password for user \"${RPI_PASSWORD_USER}\""
    echo "${RPI_PASSWORD_USER}:${RPI_PASSWORD_PW}" | sudo chpasswd \
        -root "$(abspath "${RPI_ROOT}")" \
        --crypt-method "${RPI_PASSWORD_CRYPT_METHOD}"
}
