#!/bin/bash

# change password on image

# default options
RPI_PASSWORD_USER="${RPI_PASSWORD_USER:=pi}"
RPI_PASSWORD_PW="${RPI_PASSWORD_PW:=""}"
RPI_PASSWORD_CRYPT_METHOD="${RPI_PASSWORD_CRYPT_METHOD:=SHA512}"


function rpi_password_prerun() {
    [[ -n "${RPI_PASSWORD_USER}" ]] || error "no USER set. password plugin"

    if [[ -z "${RPI_PASSWORD_PW}" ]] ; then
        # interactively get password
        log "enter password: "
        read -r -s password_one
        log "enter password again: "
        read -r -s password_two
        [[ "${password_one}" == "${password_two}" ]] || error "passwords don't match. password plugin"
        # use this password
        RPI_PASSWORD_PW="${password_one}"
        unset password_one
        unset password_two
    fi

    return 0
}

function rpi_password_run() {
    log " setting password for user \"${RPI_PASSWORD_USER}\""
    rootpath="$(realpath "${RPI_ROOT}")"
    echo "${RPI_PASSWORD_USER}:${RPI_PASSWORD_PW}" | sudo chpasswd \
        --root "${rootpath}" \
        --crypt-method "${RPI_PASSWORD_CRYPT_METHOD}"
}

function rpi_password_description() {
    echo "change password on image"
}

function rpi_password_help_params() {
    help_param "RPI_PASSWORD_USER" "the user to change the password from"
    help_param "RPI_PASSWORD_PW" "the password (empty for interactive input)"
    help_param "RPI_PASSWORD_CRYPT_METHOD" "crypt method"
}
