#!/bin/bash

# reduce power usage in default configuration

disable_services=( \
    "avahi-daemon" \
    "triggerhappy" \
    "bluetooth" \
    "hciuart" \
    "bluetooth.target" \
    "dbus" \
    "keyboard-setup" \
    "cryptsetup.target" \
    "nfs-client.target" \
    "apt-daily-upgrade.timer" \
    "apt-daily.timer" \
    "man-db.timer")

# ---------------------------------------------------------------------
function rpi_powersave_prerun() {
    load_plugin "systemctl"
    load_plugin "config"
}

function rpi_powersave_run() {
    services="${disable_services[@]}"
    RPI_SYSTEMCTL_CMDS=("disable ${services}")
    rpi_systemctl_run || error "systemctl disable"

    # turn off unneeded things
    RPI_CONFIG_ADD=(
        "dtparam=audio=off" \
        "disable_auto_turbo=1" \
        "dtoverlay=disable-bluetooth" \
        "dtparam=i2c_arm=off" \
        "dtparam=i2s=off" \
        "dtparam=spi=off" \
        "start_x=0"
    )
    rpi_config_run || error "config.txt modification"
}
