#!/bin/bash

# download & mount raspbian image

# @example
# download raspbian full
# RPI_RASPBIAN_FLAVOR="full"


# default options
RPI_DOWNLOAD_RASPBIAN_FLAVOR="${RPI_DOWNLOAD_RASPBIAN_FLAVOR:=lite}"
RPI_DOWNLOAD_RASPBIAN_URL="${RPI_DOWNLOAD_RASPBIAN_URL:=https://downloads.raspberrypi.org/raspbian_${RPI_DOWNLOAD_RASPBIAN_FLAVOR}_latest}"

# load dependencies
plugin_load download || return 1
plugin_load loopback || return 1


function rpi_raspbian_prerun() {
    # check arguments
    [[ -n "${RPI_DOWNLOAD_RASPBIAN_FLAVOR}" ]] || error "RPI_DOWNLOAD_RASPBIAN_FLAVOR check"
    [[ -n "${RPI_DOWNLOAD_RASPBIAN_URL:=}" ]] || error "RPI_DOWNLOAD_RASPBIAN_URL check"
}

function rpi_raspbian_run() {
    local name="raspbian-${RPI_DOWNLOAD_RASPBIAN_FLAVOR}.img"
    local dest="${RPI_WORKDIR}/${name}"

    echo " downloading ${RPI_DOWNLOAD_RASPBIAN_URL} ..."

    # already downloaded?
    if ! [[ -f "${dest}" ]] ; then
      local tmpfile
      tmpfile="$(TMPDIR=${RPI_TMPDIR} mktemp || error mktemp)"
      # download
      rpi_download_file "${RPI_DOWNLOAD_RASPBIAN_URL}" "${tmpfile}" || error "download ${_}"
      # unzip
      echo " unzipping \"${tmpfile}\""
      unzip "${tmpfile}" || error unzip
      sync
      rm "${tmpfile}" || error rm
      mv ./*raspbian-*.img "${dest}" || error mv
    fi

    # mount image
    echo " setting up loopback for ${dest}"
    rpi_loopback_setup "${dest}" || return 1
    rpi_loopback_mount || return 1
    # read os-release
    . "${RPI_ROOT}/etc/os-release"

    return 0
}

function rpi_raspbian_postrun() {
    echo " cleaning up..."
    # cleanup os-release
    unset PRETTY_NAME
    unset NAME
    unset VERSION_ID
    unset VERSION
    unset ID
    unset ID_LIKE
    unset HOME_URL
    unset SUPPORT_URL
    unset BUG_REPORT_URL
    # tear down loopback device & unmount partitions
    rpi_loopback_umount
    rpi_loopback_cleanup
}

function rpi_raspbian_description() {
    echo "download raspbian image"
}

function rpi_raspbian_help_vars() {
    help_var "RPI_DOWNLOAD_RASPBIAN_FLAVOR" "flavor of raspbian to use: lite or full"
    help_var "RPI_DOWNLOAD_RASPBIAN_URL" "alternative download URL or local path to downloaded zip"
}

