#!/bin/bash

# run command on image

# @example
# print a custom message once
# RPI_RUN_ONCE=true
# RPI_RUN=(
#     'echo "*********************************************************"'
#     'echo "Welcome to this install."'
#     'echo "It is $(date) and we are about to bake this pi."'
#     'echo "Please standby..."'
# )


# default options
RPI_RUN_PHASE="${RPI_RUN_PHASE:=login}"

to_array RPI_RUN

# load dependencies
plugin_load append || return 1
plugin_load remove || return 1
plugin_load chown || return 1


function rpi_run_prerun() {
    [[ -n "${RPI_RUN_PHASE}" ]] || error "RPI_RUN_PHASE unset."
    [[ -n "${RPI_RUN}" ]] || error "RPI_RUN unset."
    case "${RPI_RUN_PHASE}" in
        "bake")
            ;;

        "login")
            ;;

        "boot")
            ;;

        ?|*)
            error "invalid RPI_RUN_PHASE. Use one of bake, boot, login"
    esac
}

function rpi_run_run() {
        rpi_run "${RPI_RUN[@]}"
}

function rpi_run_description() {
    echo "run commands on image after boot, login or manually"
}

function rpi_run_help_params() {
    help_param "RPI_RUN" "command or path to script to run"
    help_param "RPI_RUN_PHASE" "boot (run on boot), login (run on login), bake (run on host during image generation)"
    help_param "RPI_RUN_ONCE" "only run once if set"
}

# ---------------------------------------------------------------------
# run command on login
function rpi_run_on_login() {
    for cmd in "$@" ; do
        rpi_append_to_file "${cmd}" "${RPI_ROOT}/home/pi/.bashrc" || error "rpi_append_to_file"
        log "(login) cmd installed: \"${cmd}\""
    done
}

# run command once upon first login
function rpi_run_on_first_login() {
    [[ -n "$*" ]] || error "missing argument"
    local once_script="/home/pi/.bootstrap_run_on_first_login"
    # prepare script
    if ! [[ -f "${RPI_ROOT}/${once_script}" ]] ; then
        # call script from .bashrc
        rpi_run_on_login "if [[ -f \"${once_script}\" ]] ; then echo \"executing first-time setup...\" ;  time /bin/bash -c \"${once_script} && rm ${once_script} && rm -rf /home/pi/bootstrap-dist\" ; echo \"Done. Please reboot now.\" ; fi"
        sudo touch "${RPI_ROOT}/${once_script}" || error "touch"
        sudo chmod +x "${RPI_ROOT}/${once_script}" || error "sudo chmod +x"
        sudo chown root:root "${RPI_ROOT}/${once_script}" || error "chown"
    fi
    for cmd in "$@" ; do
        # append to script
        rpi_append_to_file "echo -e '--------------------------------------\nexecuting: ${cmd}\n--------------------------------------'" "${RPI_ROOT}/${once_script}"
        rpi_append_to_file "${cmd} || exit 1"         "${RPI_ROOT}/${once_script}"
        rpi_chown_pi "${once_script}" || error "chown"
        log "(first login) cmd installed: \"${cmd}\""
    done
}

# run on every boot
function rpi_run_on_boot() {
    # remove "exit 0" at the end if it's there, so we
    # can simply append commands
    rpi_remove_pattern_from_file "exit 0" "${RPI_ROOT}/etc/rc.local" || error "remove exit from rc.local"
    for cmd in "$@" ; do
        rpi_append_to_file "${cmd}" "${RPI_ROOT}/etc/rc.local" || error "append ${cmd} to rc.local"
        log "(boot) cmd installed: \"${cmd}\""
    done
}

# run command once upon first boot
function rpi_run_on_first_boot() {
    [[ -n "$*" ]] || error "missing argument"
    local once_script="/home/pi/.bootstrap_run_on_first_boot"
    # prepare script
    if ! [[ -f "${RPI_ROOT}/${once_script}" ]] ; then
        # call script from /etc/rc.local
        rpi_run_on_boot "if [[ -f \"${once_script}\" ]] ; then echo \"executing first-time setup...\" ; time /bin/bash -c \"${once_script} && rm ${once_script} && rm -rf /home/pi/bootstrap-dist\" ; echo \"Done. Please reboot now.\" ; fi"
        sudo touch "${RPI_ROOT}/${once_script}" || error "touch"
        sudo chmod +x "${RPI_ROOT}/${once_script}" || error "sudo chmod +x"
        sudo chown root:root "${RPI_ROOT}/${once_script}" || error "chown"
    fi
    for cmd in "$@" ; do
        # append to script
        rpi_append_to_file "echo -e '--------------------------------------\nexecuting: ${cmd}\n--------------------------------------'" "${RPI_ROOT}/${once_script}"
        rpi_append_to_file "${cmd} || exit 1"         "${RPI_ROOT}/${once_script}"
        rpi_chown_pi "${once_script}" || error "chown"
        log "(first boot) cmd installed: \"${cmd}\""
    done
}

# output command to once-script
function rpi_run_on_bake() {
    for cmd in "$@" ; do
        log "running: \"${cmd}\""
        ( eval "${cmd}" ) || error "${cmd}"
    done
}

# run command (either on boot or on login)
function rpi_run() {
    [[ -n "$*" ]] || error "missing argument"
    case "${RPI_RUN_PHASE}" in
        "bake")
            rpi_run_on_bake "$@"
            ;;

        "login")
            if [[ -n "${RPI_RUN_ONCE}" ]] ; then
                rpi_run_on_first_login "$@"
            else
                rpi_run_on_login "$@"
            fi
            ;;

        "boot")
            if [[ -n "${RPI_RUN_ONCE}" ]] ; then
                rpi_run_on_first_boot "$@"
            else
                rpi_run_on_boot "$@"
            fi
            ;;

        ?|*)
            error "invalid RPI_RUN_PHASE."
    esac
}
