#!/bin/bash

# run systemctl commands

RPI_SYSTEMCTL_CMDS="${RPI_SYSTEMCTL_CMDS:=""}"


function rpi_systemctl_prerun() {
    [[ -n "${RPI_SYSTEMCTL_CMDS}" ]] || { warn "RPI_SYSTEMCTL_CMDS must be set" ; return 1 ; }
    return 0
}

function rpi_systemctl_run() {
    for cmd in "${RPI_SYSTEMCTL_CMDS[@]}" ; do
        run_once "sudo systemctl ${cmd}" || error "install systemctl ${cmd}"
    done
}

function rpi_systemctl_description() {
    echo "run systemctl commands once"
}

function rpi_systemctl_help_vars() {
    local vars=(
        "RPI_SYSTEMCTL_CMDS|array of systemctl commands|${RPI_SYSTEMCTL_CMDS}"
    )
    help_for_vars "${vars[@]}"
}
