#!/bin/bash

# run systemctl commands

# default options
RPI_SYSTEMCTL_CMDS="${RPI_SYSTEMCTL_CMDS:=""}"

# load dependencies
plugin_load run || return 1


function rpi_systemctl_prerun() {
    [[ -n "${RPI_SYSTEMCTL_CMDS}" ]] || { warn "RPI_SYSTEMCTL_CMDS must be set" ; return 1 ; }
    return 0
}

function rpi_systemctl_run() {
    for cmd in "${RPI_SYSTEMCTL_CMDS[@]}" ; do
        rpi_run_once "sudo systemctl ${cmd}" || error "install systemctl ${cmd}"
    done
}

function rpi_systemctl_description() {
    echo "run systemctl commands once"
}

function rpi_systemctl_help_vars() {
    help_var "RPI_SYSTEMCTL_CMDS" "array of systemctl commands"
}
