#!/bin/sh

# bootstrap wifi configuation for rpi image

function rpi_wifi_prerun() {
    true
}

function rpi_wifi_run() {
    # create wpa_supplicant.conf from config parameters
    if [ -n "${RPI_WIFI_SSID}" ] && [ -n "${RPI_WIFI_PSK}" ] ; then
        echo " creating /etc/wpa_supplicant.conf"
        # optionally set country
        country=""
        [ -n "${RPI_WIFI_COUNTRY}" ] && country="country=\"${RPI_WIFI_COUNTRY}\""
        append_stdin "${RPI_ROOT}/etc/wpa_supplicant/wpa_supplicant.conf" << EOF
$country
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network=\{
\ \ \ \ ssid="$RPI_WIFI_SSID"
\ \ \ \ psk="$RPI_WIFI_PSK"
\}
EOF
    fi

    # copy from distfiles
    cp_from_dist_if_exist "/etc/wpa_supplicant/wpa_supplicant.conf"

    # copy to boot
    sudo cp "${RPI_ROOT}/etc/wpa_supplicant/wpa_supplicant.conf" "${RPI_BOOT}/"

    return 0
}
