#!/bin/bash

# bootstrap wifi configuation for rpi image

# @example
# configure wifi
# RPI_WIFI_SSID="name-of-the-network"
# RPI_WIFI_PSK="very_secret_password"


# default options
default_country="$(locale country_ab2)"
RPI_WIFI_SSID="${RPI_WIFI_SSID:=}"
RPI_WIFI_PSK="${RPI_WIFI_PSK:=}"
RPI_WIFI_COUNTRY="${RPI_WIFI_COUNTRY:=${default_country}}"
RPI_WIFI_POWERSAVE="${RPI_WIFI_POWERSAVE:=false}"

# load dependencies
plugin_load append || return 1
plugin_load dist || return 1
plugin_load run || return 1


function rpi_wifi_prerun() {
    true
}

function rpi_wifi_run() {

    # create wpa_supplicant.conf from config parameters
    if [[ -n "${RPI_WIFI_SSID}" ]] && [[ -n "${RPI_WIFI_PSK}" ]] ; then
        log "creating /etc/wpa_supplicant.conf"
        # optionally set country
        local country="#country=\"${RPI_WIFI_COUNTRY}\""
        [[ -n "${RPI_WIFI_COUNTRY}" ]] && country="country=\"${RPI_WIFI_COUNTRY}\""
        rpi_append_stdin "${RPI_ROOT}/etc/wpa_supplicant/wpa_supplicant.conf" << EOF
${country}
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
        ssid="${RPI_WIFI_SSID}"
        psk="${RPI_WIFI_PSK}"
}
EOF
    fi

    # turn off powersaving?
    local powersave
    if [[ "${RPI_WIFI_POWERSAVE}" == "false" ]] ; then
        powersave="on"
    elif [[ "${RPI_WIFI_POWERSAVE}" == "true" ]] ; then
        powersave="off"
    fi
    rpi_run_on_boot "# turn off wifi power saving" || error "run_on_boot"
    rpi_run_on_boot "iw dev wlan0 set power_save ${powersave}" || error "run_on_boot"

    # copy from distfiles
    rpi_dist_cp_if_exist "/etc/wpa_supplicant/wpa_supplicant.conf"

    # copy to boot
    sudo cp "${RPI_ROOT}/etc/wpa_supplicant/wpa_supplicant.conf" "${RPI_BOOT}/"

    return 0
}

function rpi_wifi_description() {
    echo "configure wifi"
}

function rpi_wifi_help_params() {
    help_param "RPI_WIFI_SSID" "SSID of network"
    help_param "RPI_WIFI_PSK" "network password"
    help_param "RPI_WIFI_COUNTRY" "wifi country standard. optional."
    help_param "RPI_WIFI_POWERSAVE" "turn wifi powersave on/off on boot"
}

function rpi_wifi_help_distfiles() {
    help_distfile "/etc/wpa_supplicant/wpa_supplicant.conf"
}
