#!/bin/bash

# bootstrap wifi configuation for rpi image

RPI_WIFI_SSID="${RPI_WIFI_SSID:=}"
RPI_WIFI_PSK="${RPI_WIFI_PSK:=}"
RPI_WIFI_COUNTRY="${RPI_WIFI_COUNTRY:=}"
RPI_WIFI_POWERSAVE="${RPI_WIFI_POWERSAVE:=false}"


function rpi_wifi_prerun() {
    true
}

function rpi_wifi_run() {
    local powersave

    # create wpa_supplicant.conf from config parameters
    if [ -n "${RPI_WIFI_SSID}" ] && [ -n "${RPI_WIFI_PSK}" ] ; then
        echo " creating /etc/wpa_supplicant.conf"
        # optionally set country
        local country="#country=\"${RPI_WIFI_COUNTRY}\""
        [ -n "${RPI_WIFI_COUNTRY}" ] && country="country=\"${RPI_WIFI_COUNTRY}\""
        append_stdin "${RPI_ROOT}/etc/wpa_supplicant/wpa_supplicant.conf" << EOF
${country}
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network=\{
\ \ \ \ ssid="${RPI_WIFI_SSID}"
\ \ \ \ psk="${RPI_WIFI_PSK}"
\}
EOF
    fi

    # turn off powersaving?
    if [ "${RPI_WIFI_POWERSAVE}" == "false" ] ; then
        powersave="on"
    elif [ "${RPI_WIFI_POWERSAVE}" == "true" ] ; then
        powersave="off"
    fi

    run_on_boot "# turn off wifi power saving\niw dev wlan0 set power_save ${powersave}" || error "run_on_boot"

    # copy from distfiles
    cp_from_dist_if_exist "/etc/wpa_supplicant/wpa_supplicant.conf"

    # copy to boot
    sudo cp "${RPI_ROOT}/etc/wpa_supplicant/wpa_supplicant.conf" "${RPI_BOOT}/"

    return 0
}

function rpi_wifi_description() {
    echo "configure wifi"
}

function rpi_wifi_help_vars() {
    local vars=( \
        "RPI_WIFI_SSID|SSID of network|${RPI_WIFI_SSID}"
        "RPI_WIFI_PSK|network password|${RPI_WIFI_PSK}"
        "RPI_WIFI_COUNTRY|wifi country standard. optional.|${RPI_WIFI_COUNTRY}"
        "RPI_WIFI_POWERSAVE|turn wifi powersave on/off on boot|${RPI_WIFI_POWERSAVE}"
    )
    help_for_vars "${vars[@]}"
}

function rpi_wifi_help_distfiles() {
    help_for_distfiles "/etc/wpa_supplicant/wpa_supplicant.conf"
}
