# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TERM: linux
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # seetup
      - name: Add user to disk group
        run: sudo gpasswd -a "$USER" disk

      # shellcheck
      - name: Install shellcheck
        run: sudo apt install shellcheck

      # some tests
      - name: run tests
        run: sudo ./test/test.sh
      - name: build examples/complete-test
        run: |
          cd examples/complete-test
          ./bootstrap.sh
